- hosts: doritos
  user: ubi-lab
  sudo: yes
  tasks:
    - name: register CUDA repository
      deb: http://developer.download.nvidia.com/compute/cuda/repos/ubuntu1404/x86_64/cuda-repo-ubuntu1404_7.5-18_amd64.deb
    - name: install CUDA
      apt: name=cuda update_cache=yes